# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'adicarter.ui'
#
# Created by: PyQt5 UI code generator 5.9
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(1281, 498)
        self.txtSKU = QtWidgets.QLineEdit(Dialog)
        self.txtSKU.setGeometry(QtCore.QRect(90, 400, 191, 21))
        font = QtGui.QFont()
        font.setFamily("YEEZY TSTAR")
        font.setPointSize(14)
        self.txtSKU.setFont(font)
        self.txtSKU.setObjectName("txtSKU")
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(20, 402, 60, 16))
        font = QtGui.QFont()
        font.setFamily("YEEZY TSTAR")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.boxSize = QtWidgets.QComboBox(Dialog)
        self.boxSize.setGeometry(QtCore.QRect(90, 430, 191, 26))
        font = QtGui.QFont()
        font.setFamily("YEEZY TSTAR")
        font.setPointSize(14)
        self.boxSize.setFont(font)
        self.boxSize.setObjectName("boxSize")
        self.boxSize.addItem("")
        self.boxSize.addItem("")
        self.boxSize.addItem("")
        self.boxSize.addItem("")
        self.boxSize.addItem("")
        self.boxSize.addItem("")
        self.boxSize.addItem("")
        self.boxSize.addItem("")
        self.boxSize.addItem("")
        self.boxSize.addItem("")
        self.boxSize.addItem("")
        self.boxSize.addItem("")
        self.boxSize.addItem("")
        self.boxSize.addItem("")
        self.boxSize.addItem("")
        self.boxSize.addItem("")
        self.boxSize.addItem("")
        self.boxSize.addItem("")
        self.boxSize.addItem("")
        self.boxSize.addItem("")
        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(20, 434, 60, 16))
        font = QtGui.QFont()
        font.setFamily("YEEZY TSTAR")
        font.setPointSize(14)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.btnAddTask = QtWidgets.QPushButton(Dialog)
        self.btnAddTask.setGeometry(QtCore.QRect(20, 460, 261, 32))
        font = QtGui.QFont()
        font.setFamily("YEEZY TSTAR")
        font.setPointSize(14)
        self.btnAddTask.setFont(font)
        self.btnAddTask.setAutoDefault(False)
        self.btnAddTask.setObjectName("btnAddTask")
        self.tableProxies = QtWidgets.QTableWidget(Dialog)
        self.tableProxies.setGeometry(QtCore.QRect(20, 11, 261, 141))
        font = QtGui.QFont()
        font.setFamily("YEEZY TSTAR")
        font.setPointSize(14)
        self.tableProxies.setFont(font)
        self.tableProxies.setObjectName("tableProxies")
        self.tableProxies.setColumnCount(2)
        self.tableProxies.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableProxies.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableProxies.setHorizontalHeaderItem(1, item)
        self.tableProxies.horizontalHeader().setDefaultSectionSize(115)
        self.tableProxies.horizontalHeader().setStretchLastSection(True)
        self.btnProxies = QtWidgets.QPushButton(Dialog)
        self.btnProxies.setGeometry(QtCore.QRect(20, 160, 261, 32))
        font = QtGui.QFont()
        font.setFamily("YEEZY TSTAR")
        font.setPointSize(14)
        self.btnProxies.setFont(font)
        self.btnProxies.setAutoDefault(False)
        self.btnProxies.setObjectName("btnProxies")
        self.btnAccounts = QtWidgets.QPushButton(Dialog)
        self.btnAccounts.setGeometry(QtCore.QRect(20, 350, 261, 32))
        font = QtGui.QFont()
        font.setFamily("YEEZY TSTAR")
        font.setPointSize(14)
        self.btnAccounts.setFont(font)
        self.btnAccounts.setAutoDefault(False)
        self.btnAccounts.setObjectName("btnAccounts")
        self.tableAccounts = QtWidgets.QTableWidget(Dialog)
        self.tableAccounts.setGeometry(QtCore.QRect(20, 200, 261, 141))
        font = QtGui.QFont()
        font.setFamily("YEEZY TSTAR")
        font.setPointSize(14)
        self.tableAccounts.setFont(font)
        self.tableAccounts.setObjectName("tableAccounts")
        self.tableAccounts.setColumnCount(2)
        self.tableAccounts.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableAccounts.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableAccounts.setHorizontalHeaderItem(1, item)
        self.tableAccounts.horizontalHeader().setDefaultSectionSize(115)
        self.tableAccounts.horizontalHeader().setStretchLastSection(True)
        self.tableTasks = QtWidgets.QTableWidget(Dialog)
        self.tableTasks.setGeometry(QtCore.QRect(300, 10, 971, 441))
        font = QtGui.QFont()
        font.setFamily("YEEZY TSTAR")
        font.setPointSize(14)
        self.tableTasks.setFont(font)
        self.tableTasks.setObjectName("tableTasks")
        self.tableTasks.setColumnCount(7)
        self.tableTasks.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tableTasks.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTasks.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTasks.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTasks.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTasks.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTasks.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableTasks.setHorizontalHeaderItem(6, item)
        self.tableTasks.horizontalHeader().setDefaultSectionSize(130)
        self.tableTasks.horizontalHeader().setStretchLastSection(True)
        self.timeStart = QtWidgets.QTimeEdit(Dialog)
        self.timeStart.setGeometry(QtCore.QRect(1150, 463, 118, 24))
        font = QtGui.QFont()
        font.setFamily("YEEZY TSTAR")
        font.setPointSize(14)
        self.timeStart.setFont(font)
        self.timeStart.setObjectName("timeStart")
        self.btnStartTask = QtWidgets.QPushButton(Dialog)
        self.btnStartTask.setGeometry(QtCore.QRect(1030, 460, 113, 32))
        font = QtGui.QFont()
        font.setFamily("YEEZY TSTAR")
        font.setPointSize(14)
        self.btnStartTask.setFont(font)
        self.btnStartTask.setAutoDefault(False)
        self.btnStartTask.setObjectName("btnStartTask")
        self.btnRemoveTask = QtWidgets.QPushButton(Dialog)
        self.btnRemoveTask.setGeometry(QtCore.QRect(300, 460, 113, 32))
        font = QtGui.QFont()
        font.setFamily("YEEZY TSTAR")
        font.setPointSize(14)
        self.btnRemoveTask.setFont(font)
        self.btnRemoveTask.setAutoDefault(False)
        self.btnRemoveTask.setObjectName("btnRemoveTask")
        self.btnRemoveAll = QtWidgets.QPushButton(Dialog)
        self.btnRemoveAll.setGeometry(QtCore.QRect(410, 460, 141, 32))
        font = QtGui.QFont()
        font.setFamily("YEEZY TSTAR")
        font.setPointSize(14)
        self.btnRemoveAll.setFont(font)
        self.btnRemoveAll.setAutoDefault(False)
        self.btnRemoveAll.setObjectName("btnRemoveAll")
        self.line = QtWidgets.QFrame(Dialog)
        self.line.setGeometry(QtCore.QRect(0, 380, 301, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dyspo"))
        self.label.setText(_translate("Dialog", "SKU"))
        self.boxSize.setItemText(0, _translate("Dialog", "4.0"))
        self.boxSize.setItemText(1, _translate("Dialog", "4.5"))
        self.boxSize.setItemText(2, _translate("Dialog", "5.0"))
        self.boxSize.setItemText(3, _translate("Dialog", "5.5"))
        self.boxSize.setItemText(4, _translate("Dialog", "6.0"))
        self.boxSize.setItemText(5, _translate("Dialog", "6.5"))
        self.boxSize.setItemText(6, _translate("Dialog", "7.0"))
        self.boxSize.setItemText(7, _translate("Dialog", "7.5"))
        self.boxSize.setItemText(8, _translate("Dialog", "8.0"))
        self.boxSize.setItemText(9, _translate("Dialog", "8.5"))
        self.boxSize.setItemText(10, _translate("Dialog", "9.0"))
        self.boxSize.setItemText(11, _translate("Dialog", "9.5"))
        self.boxSize.setItemText(12, _translate("Dialog", "10.0"))
        self.boxSize.setItemText(13, _translate("Dialog", "10.5"))
        self.boxSize.setItemText(14, _translate("Dialog", "11.0"))
        self.boxSize.setItemText(15, _translate("Dialog", "11.5"))
        self.boxSize.setItemText(16, _translate("Dialog", "12.0"))
        self.boxSize.setItemText(17, _translate("Dialog", "12.5"))
        self.boxSize.setItemText(18, _translate("Dialog", "13.0"))
        self.boxSize.setItemText(19, _translate("Dialog", "FSR"))
        self.label_2.setText(_translate("Dialog", "Size"))
        self.btnAddTask.setText(_translate("Dialog", "Add Task"))
        item = self.tableProxies.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Type"))
        item = self.tableProxies.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Address"))
        self.btnProxies.setText(_translate("Dialog", "Load Proxies"))
        self.btnAccounts.setText(_translate("Dialog", "Load Accounts"))
        item = self.tableAccounts.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Email"))
        item = self.tableAccounts.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "Password"))
        item = self.tableTasks.horizontalHeaderItem(0)
        item.setText(_translate("Dialog", "Status"))
        item = self.tableTasks.horizontalHeaderItem(1)
        item.setText(_translate("Dialog", "SKU"))
        item = self.tableTasks.horizontalHeaderItem(2)
        item.setText(_translate("Dialog", "Size"))
        item = self.tableTasks.horizontalHeaderItem(3)
        item.setText(_translate("Dialog", "Method"))
        item = self.tableTasks.horizontalHeaderItem(4)
        item.setText(_translate("Dialog", "Proxy"))
        item = self.tableTasks.horizontalHeaderItem(5)
        item.setText(_translate("Dialog", "Email"))
        item = self.tableTasks.horizontalHeaderItem(6)
        item.setText(_translate("Dialog", "Password"))
        self.btnStartTask.setText(_translate("Dialog", "Start Tasks @"))
        self.btnRemoveTask.setText(_translate("Dialog", "Remove Task"))
        self.btnRemoveAll.setText(_translate("Dialog", "Remove All Tasks"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
